workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
      when: never
    - when: always

...
run_unit_tests:
  stage: test
  before_script:
    - echo "Preparing test data..."
  script:
    - echo "Running pipeline for branch $CI_COMMIT_BRANCH" 
    - echo "Running unit tests..."
  after_script:
    - echo "Cleaning up temporary files..."
