.deploy:
  tags: 
    - ec2
    - shell
    - remote
  variables:
    SSH_KEY: ""    
  script:
    - echo $SSH_PRIVATE_KEY
    - echo "----------------------"
    - echo ${SSH_PRIVATE_KEY}
    - echo "----------------------"
    - echo $SSH_KEY
    - echo "----------------------"
    - echo ${SSH_KEY}
    

deploy_to_dev:
  extends: .deploy
  variables:
    SSH_KEY: $${SSH_PRIVATE_KEY}
