

.deploy:
  tags: 
    - ec2
    - shell
    - remote
  variables:
    SSH_KEY: ""
  before_script:
    - echo $SSH_KEY
    - chmod 400 $SSH_KEY
  script:
    - echo "blaaa---------"
    - echo $SSH_PRIVATE_KEY

deploy_to_dev:
  extends: .deploy
  variables:
    SSH_KEY: $SSH_PRIVATE_KEY


