run_tests:
  image: node:17-alpine3.14
  tags:
    - ec2
    - docker
    - remote
  before_script:
    - cd app
    - npm install
  script:
    - npm run test
  artifacts:
    when: always
    reports:
      junit:
        - app/junit.xml

build_image:
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:1.0

push_image:
  script:
    - docker push ${CI_REGISTRY_IMAGE}:1.0
