stages:
  - test
  - build

run_tests:
  stage: test
  image: node:17-alpine3.14
  tags:
    - ec2
    - docker
    - remote
  before_script:
    - cd app
    - npm install
  script:
    - npm run test
  artifacts:
    when: always
    reports:
      junit:
        - app/junit.xml

build_image:
  stage: build
  tags:
    - ec2
    - shell
    - remote
  before_script:
    - echo $USER
    - sudo usermod -aG docker $USER
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:1.0

push_image:
  stage: build
  needs:
    - build_image
  tags:
    - ec2
    - shell
    - remote
  script:
    - docker push ${CI_REGISTRY_IMAGE}:1.0
