

.deploy:
  tags: 
    - ec2
    - shell
    - remote
  variables:
    SSH_KEY: ""
  before_script:
    - echo $SSH_KEY
    - chmod 400 $SSH_KEY
  script:
    - echo "blaaa---------"
    - echo $SSH_PRIVATE_KEY

deploy_to_dev:
  extends: .deploy
  variables:
    SSH_KEY: $SSH_PRIVATE_KEY


run_functional_tests:
  stage: deploy_dev
  needs:
    - deploy_to_dev
  script: 
    - wrong-command "running functional tests"

deploy_to_staging:
  extends: .deploy
  stage: deploy_staging
  needs: 
    - build_image
    - run_functional_tests
  variables:
    SSH_KEY: $SSH_PRIVATE_KEY
    SERVER_HOST: $STAGING_SERVER_HOST
    DEPLOY_ENV: staging
    APP_PORT: 4000
    ENDPOINT: $STAGING_ENDPOINT

run_performance_tests:
  stage: deploy_staging
  needs:
    - deploy_to_staging
  script: 
    - echo "Running performance tests"

deploy_to_prod:
  extends: .deploy
  stage: deploy_prod
  needs:
    - build_image
    - run_performance_tests
  variables:
    SSH_KEY: $SSH_PRIVATE_KEY
    SERVER_HOST: $PROD_SERVER_HOST
    DEPLOY_ENV: production
    APP_PORT: 5000
    ENDPOINT: $PROD_ENDPOINT
  when: manual



include:
  - template: Jobs/SAST.gitlab-ci.yml
