workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: never
    - when: always

stages:
  - test
  - build 
  - deploy

run_unit_tests:
  stage: test
  
  image: node:16-alpine
  before_script:
    - cd app
    - npm install
  script:
    - npm test
  artifacts:
    when: always
    paths:
      - app/junit.xml
    reports: 
      junit: app/junit.xml
